### ISSUE TITLE
height of textfield

### ISSUE THREAD

**Issue by lzakon** [jlorente/yii2-widget-remainingcharacters#1]
Hello, i try to use yii2-widget-remainingcharacters widget in _form.php for TextIput field. I use: 'type' => \jlorente\remainingcharacters\RemainingCharacters::INPUT_TEXTAREA.

The height of rendered field is differed from height  for standard yii2 fields.  Help me please solve this issue.
 
Thanks in advance

**Comment by jlorente** [comment]
I don't understand your problem. You are using a textarea, that is in fact higher than the other form fields. Try to use:  'type' => \jlorente\remainingcharacters\RemainingCharacters::INPUT_TEXT to render a common input field. If you want to set another height to the textarea field, you can always pass a rows variable into the options array property.
